name: CI Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install black isort flake8 mypy pytest pytest-asyncio

      - name: Run Black
        run: black --check .

      - name: Run Isort
        run: isort --check-only --profile black .

      - name: Run Flake8
        run: flake8 . --exclude=.venv,venv,db,pgdata --max-line-length=88

      - name: Run Mypy
        run: mypy . --ignore-missing-imports --exclude "(venv|\.venv|db|pgdata)"

      - name: Run Tests
        run: pytest -v -W ignore::DeprecationWarning
